import { type MobId } from "../lib/mob.mapping";
import { type Rune } from "./rune";

export type Mob = {
  unit_id: number;
  wizard_id: number;
  island_id: number;
  pos_x: number;
  pos_y: number;
  building_id: number;
  unit_master_id: MobId;
  unit_level: number;
  class: number;
  con: number;
  atk: number;
  def: number;
  spd: number;
  resist: number;
  accuracy: number;
  critical_rate: number;
  critical_damage: number;
  experience: number;
  exp_gained: number;
  exp_gain_rate: number;
  skills: [number, number][];
  runes: Rune[];
  artifacts: unknown;
  costume_master_id: number;
  trans_items: unknown;
  attribute: number;
  create_time: string;
  source: number;
  homunculus: 0 | 1;
  homunculus_name: string;
  unit_index: null;
  awakening_info: unknown;
};
